export const billList = [{
    id: 1,
    comments: Math.floor(Math.random() * 100) + 1,
    title: 'ObamaCare Repeal Act',
    text: 'aka. farewell Obamacare. Approximately 24 million Americans will be without access to health insurance.',
    notations: Math.floor(Math.random() * 100) + 1,
    number: 'H.R. 175',
  },
  {
    id: 2,
    comments: Math.floor(Math.random() * 100) + 1,
    title: 'National Clinical Care Commission Act',
    text: 'Energy Efficient Government Technology Act',
    notations: Math.floor(Math.random() * 100) + 1,
    number: 'H.R. 301',
  },
  {
    id: 3,
    comments: Math.floor(Math.random() * 100) + 1,
    title: 'Energy Efficient Government Technology Act',
    text: 'Federal agencies implementation of energy-efficient and energy-saving information technology',
    notations: Math.floor(Math.random() * 100) + 1,
    number: 'H.R. 124',
  },
  {
    id: 4,
    comments: Math.floor(Math.random() * 100) + 1,
    title: 'ObamaCare Repeal Act',
    text: 'aka. farewell Obamacare. Approximately 24 million Americans will be without access to health insurance.',
    notations: Math.floor(Math.random() * 100) + 1,
    number: 'H.R. 316',
  },
  {
    id: 5,
    comments: Math.floor(Math.random() * 100) + 1,
    title: 'National Clinical Care Commission Act',
    text: 'Energy Efficient Government Technology Act',
    notations: Math.floor(Math.random() * 100) + 1,
    number: 'H.R. 285',
  },
  {
    id: 6,
    comments: Math.floor(Math.random() * 100) + 1,
    title: 'Energy Efficient Government Technology Act',
    text: 'Federal agencies implementation of energy-efficient and energy-saving information technology',
    notations: Math.floor(Math.random() * 100) + 1,
    number: 'H.R. 291',
  },
];


export const billHash = {
  '1': {
    id: 1,
    comments: Math.floor(Math.random() * 100) + 1,
    title: 'ObamaCare Repeal Act',
    text: 'aka. farewell Obamacare. Approximately 24 million Americans will be without access to health insurance.',
    notations: Math.floor(Math.random() * 100) + 1,
    number: 'H.R. 175',
  },
  '2': {
    id: 2,
    comments: Math.floor(Math.random() * 100) + 1,
    title: 'National Clinical Care Commission Act',
    text: 'Energy Efficient Government Technology Act',
    notations: Math.floor(Math.random() * 100) + 1,
    number: 'H.R. 301',
  },
  '3': {
    id: 3,
    comments: Math.floor(Math.random() * 100) + 1,
    title: 'Energy Efficient Government Technology Act',
    text: 'Federal agencies implementation of energy-efficient and energy-saving information technology',
    notations: Math.floor(Math.random() * 100) + 1,
    number: 'H.R. 124',
  },
  '4': {
    id: 4,
    comments: Math.floor(Math.random() * 100) + 1,
    title: 'ObamaCare Repeal Act',
    text: 'aka. farewell Obamacare. Approximately 24 million Americans will be without access to health insurance.',
    notations: Math.floor(Math.random() * 100) + 1,
    number: 'H.R. 316',
  },
  '5': {
    id: 5,
    comments: Math.floor(Math.random() * 100) + 1,
    title: 'National Clinical Care Commission Act',
    text: 'Energy Efficient Government Technology Act',
    notations: Math.floor(Math.random() * 100) + 1,
    number: 'H.R. 285',
  },
  '6': {
    id: 6,
    comments: Math.floor(Math.random() * 100) + 1,
    title: 'Energy Efficient Government Technology Act',
    text: 'Federal agencies implementation of energy-efficient and energy-saving information technology',
    notations: Math.floor(Math.random() * 100) + 1,
    number: 'H.R. 291',
  },
};
